image: node:7.10.1
cache:
  paths:
    - node_modules

before_script:
  - npm install -g gitbook-cli
  - gitbook fetch 3.2.3
  - gitbook install

pages:
  stage: deploy
  script:
    - gitbook build . public
  artifacts:
    paths:
      - public
  only:
    - master
